#!/usr/bin/env ruby

###
# editpost -- edit an existing post
# Updates the date in the file and opens it in iAWriter.app
# Change blog_dir and editor to customize
#
# Based on a script by Jon Canady (https://github.com/joncanady/joncanady.com)
# Covered by the WTFPL: http://sam.zoy.org/wtfpl/
###

# omit the trailing slash, please
blog_dir = "/Volumes/Freelance/projects/personal/bryanjswift.github.com"
# passed to open -a
editor = "/Applications/iA Writer.app"

require 'optparse'

optparse = OptionParser.new do |opts|

  # banner
  opts.banner = "Usage: editpost relative/path/to/YYYY-MM-DD-post.format"

  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
    exit
  end

  # Would be nice to have an option to leave a post as draft
  # If not leaving as draft move it to the appropriate directory (_posts or journal/_posts)
  # Need an option for a journal entry
  # Should also change file name if the date is different (it probably is)

end

begin
  optparse.parse!
rescue OptionParser::InvalidOption => e
  puts e
  puts o
  exit 1
end

if ARGV[0].nil?
  optparse.display
  exit 1
end

file = ARGV[0]
now = "date: #{Time.now.strftime("%Y-%m-%d %H:%M:%S")}"

puts "Updating date to #{now}"

post = "#{file}"
text = File.read(post).gsub(/date: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/, now)

File.open(post, 'w') do |f|
  f << text
end

puts "Opening post..."
system("open", "-a#{editor}", post)
exit 0
