#!/usr/bin/env ruby

###
# newpost -- creates a new Jekyll post
# Change the blog_dir variable below, and you should be set.
# For maximum win, put in ~/bin/ (and add that to your $PATH)
#
# Based on a script by Jon Canady (https://github.com/joncanady/joncanady.com)
# Covered by the WTFPL: http://sam.zoy.org/wtfpl/
###

# omit the trailing slash, please
blog_dir = "/Volumes/Freelance/projects/personal/bryanjswift.github.com"
# passed to open -a
editor = "/Applications/iA Writer.app"

require 'optparse'

options = { draft: false, format: :markdown, categories: [] }

optparse = OptionParser.new do |opts|

  # banner
  opts.banner = "Usage: newpost [options] \"title of post\""

  opts.on('-d', '--draft', 'Create post as a draft') do 
    options[:draft] = true
  end

  opts.on('-f', '--format FORMAT', [:markdown, :textile], 'Post is in [markdown|textile] (default markdown)') do |format|
    options[:format] = format
  end

  opts.on('-c', '--categories a[,b[,c]]', Array, 'List of categories') do|cats|
    options[:categories] = cats
  end

  opts.on('-j', '--journal', 'Make it a Journal entry') do
    options[:categories] << 'journal'
  end

  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
    exit
  end

end

begin
  optparse.parse!
rescue OptionParser::InvalidOption => e
  puts e
  puts o
  exit 1
end
 
if ARGV[0].nil?
  optparse.display
  exit 1
end

puts "Generating post..."

now = Time.now
date_prefix = now.strftime("%Y-%m-%d")
postname = ARGV[0].strip.downcase.gsub(/[^a-zA-Z0-9 ]/, '').gsub(/ /, '-')
categories = options[:categories]
published = false
published = options[:draft] unless categories.include?("journal")

post_dir = options[:draft] ? '_drafts' : '_posts'

post = "#{blog_dir}/#{post_dir}/#{date_prefix}-#{postname}.#{options[:format]}"
 
header = <<-END
---
layout: post
title: #{ARGV[0]}
date: #{now.strftime("%Y-%m-%d %H:%M:%S")}
published: #{published}
categories: #{categories.to_s}
---
 
END
 
File.open(post, 'w') do |f|
  f << header
end
 
puts "Opening post..."
system("open", "-a#{editor}", post)
exit 0
