title: Bryan Writes Here
author: Bryan J Swift
url: http://bryanjswift.github.com

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%A %B %o %Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: bryan.j.swift@gmail.com

root: /
permalink: /blog/:year/:title/
source: .
destination: _site

exclude: [_drafts, task, lib, config.ru, CNAME, Gemfile]
markdown: kramdown

# simulate GitHub Pages
pygments: true
safe: true
