title: Bryan Writes
author: Bryan J Swift
url: https://bryanwrit.es

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%A %B %o %Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: https://bryanwrit.es/atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: mail@bryanwrit.es

root: /
permalink: /here/:year/:title/
source: .
destination: _site

exclude: [_drafts, task, CNAME, Gemfile, Gemfile.lock, node_modules, vendor]
markdown: kramdown

index:
  count: 1

# simulate GitHub Pages
safe: true
